apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
  {{- toYaml .Values.service | nindent 2 }}