apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-producer.fullname" . }}
  labels:
    {{- include "kafka-producer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-producer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka-producer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: kafka-truststore-jks
          secret:
            secretName: truststore-jks
        - name: kafka-user-p12
          secret:
            secretName: user-p12
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/etc/kafka-credentials/kafka-truststore-jks"
              name: kafka-truststore-jks
              readOnly: true
            - mountPath: "/etc/kafka-credentials/kafka-user-p12"
              name: kafka-user-p12
              readOnly: true
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
          env:
            - name: QUARKUS_LOG_CONSOLE_JSON_PROVIDERS_CONTEXT_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: QUARKUS_LOG_CONSOLE_JSON_PROVIDERS_CONTEXT_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: QUARKUS_LOG_CONSOLE_JSON_PROVIDERS_CONTEXT_CONTAINER
              value: {{ .Chart.Name }}      
            - name: QUARKUS_LOG_CONSOLE_PROVIDERS_CONTEXT_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: QUARKUS_LOG_CONSOLE_PROVIDERS_CONTEXT_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: QUARKUS_LOG_CONSOLE_PROVIDERS_CONTEXT_CONTAINER
              value: {{ .Chart.Name }}      
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
          - configMapRef:
              name: {{ include "kafka-producer.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
