{{- if .Values.kafka.user.enabled -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: {{ .Values.kafka.user.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.server.name }}
    {{- include "YOUR_SERVICE_NAME.labels" . | nindent 4 }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: {{ .Values.kafka.user.consumer_group }}
          patternType: literal
        operation: Read
        host: '*'
      {{- range $key, $topicConfig := .Values.kafka.topics.configurations }}
        {{- range $aclKey, $aclValue := $topicConfig.user_acl }}
      - resource:
          type: topic
          name: {{ $topicConfig.name }}
          patternType: literal
        operation: {{ $aclValue }}
        host: '*'
        {{- end }}
      {{- end }}
{{- end }}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: producer-user
  labels:
    strimzi.io/cluster: kafka
  namespace: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: producer-group
          patternType: literal
        operation: All
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Create
        host: '*'
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: consumer-user
  labels:
    strimzi.io/cluster: kafka
  namespace: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: consumer-group
          patternType: literal
        operation: All
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: topic-with-user-acl
          patternType: literal
        operation: Describe
        host: '*'
