quarkus:
#  application:
#    name: myservice1-vault-referece-implementation
  kubernetes-config:
    enabled: true
    fail-on-missing-config: false
    secrets:
      ~: myservice1-ext-secrets
      enabled: true
  http:
    root-path: /
    non-application-root-path: q
  smallrye-health:
    root-path: health
    liveness-path: liveness

## environment variable
svc:
  database:
    url: "postgres://postgre@postgres-svc:5432/localdb-yaml"
