quarkus:
  http:
    root-path: /
    non-application-root-path: q
  smallrye-health:
    root-path: health
    liveness-path: liveness

## environment variable
svc:
  database:
    url: "postgres://postgre@postgres-svc:5432/localdb"
