apiVersion: v1
kind: Namespace
metadata:
  name: kafka-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-producer
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-consumer
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
