{{- if .Values.database.server.enabled -}}
{{- if eq .Values.database.service.platform  "postgresql" }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "service.name" . }}-{{ .Values.database.service.name }}
spec:
  databases:
    {{ .Values.database.service.databaseSchemaName }}: sankarganeshg
  numberOfInstances: {{ .Values.database.service.replicas }}
  postgresql:
    version: '13'
    parameters:
      wal_level: 'logical'
      max_wal_senders: '1'
      max_replication_slots: '1'
  teamId: {{ .Values.database.service.teamId }}
  users:
    {{ .Values.database.service.superUserName }}:
      - replication
    {{ .Values.database.service.databaseUserName }}:
      - superuser
      - createdb
  volume:
    size: {{ .Values.database.service.diskVolume }}
{{- end }}
{{- end }}
