apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    type: script
  name: keystore-gen
data:
  keystore-gen.sh: |
    #!/bin/sh
    keytool -keystore /etc/kafka/store/kafka-client-truststore.jks \
      -alias CARoot \
      -import \
      -file /etc/kafka/user/ca.crt \
      -storepass $KAFKA_SSL_TRUSTSTORE_PASSWORD \
      -noprompt
    keytool -importkeystore \
      -deststorepass $KAFKA_SSL_TRUSTSTORE_PASSWORD \
      -destkeypass $KAFKA_SSL_TRUSTSTORE_PASSWORD \
      -destkeystore /etc/kafka/store/kafka-client-truststore.jks \
      -srckeystore /etc/kafka/user/user.p12 \
      -srcstoretype PKCS12 \
      -srcstorepass $(cat /etc/kafka/user/user.password) \
      -noprompt
