apiVersion: v1
kind: Pod
metadata:
  labels:
    run: keystore
  name: keystore
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
  - image: fabric8/java-alpine-openjdk11-jdk
    name: keystore
    command: ['sh', '-c', 'while true; do echo "Hello World"; sleep 360; done']
    env:
    - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kafka-client-keystore
          key: keystore.password
    volumeMounts:
    - name: kafka-keystore
      mountPath: "/etc/kafka/store"
    - name: kafka-user
      mountPath: "/etc/kafka/user"
      readOnly: true
    - name: scripts
      mountPath: "/opt/kafka/bin"
      readOnly: true
  volumes:
  - name: kafka-keystore
    emptyDir: {}
  - name: kafka-user
    secret:
      secretName: scbuser1
      defaultMode: 0400
  - name: scripts
    configMap:
      name: keystore-gen
      defaultMode: 0700
