apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  pipeline-application: spinnaker

helmGlobals:
  chartHome: /home/nlsgand/workspace/local/repo/k8s/helm-charts/chartrepo

# chartHome: [Optional] Provide the path to the parent directory for local chart.

helmCharts:
- name: parent-chart
  valuesFile: ./override-values.yaml
  releaseName: platform-release

resources:
  #- https://raw.githubusercontent.com/sankarganeshgandhi/k8s/main/namespace.yaml
  #- default-docker-registry.yaml
