apiVersion: v1
kind: ConfigMap
metadata:
  name: initscript-configmap
data:
{{ (.Files.Glob "configuration/initdb.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testscript-configmap
data:
{{ (.Files.Glob "configuration/test.sh").AsConfig | indent 2 }}