apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  pipeline-application: flux

# helmGlobals:
#   chartHome: /home/nlsgand/workspace/local/repo/k8s/kafka-security-helmchart

# chartHome: [Optional] Provide the path to the parent directory for local chart.

# helmCharts:
# - name: kafka-security-helm
#   valuesFile: ./override-values.yaml
#   releaseName: platform-release
#   version: 1.1.0

helmChartInflationGenerator:
- chartName: kafka-security-helm
  chartHome: /home/nlsgand/workspace/local/repo/k8s/kafka-security-helmchart
  values: ./override-values.yaml
  releaseName: kafka-security

resources:
  #- https://raw.githubusercontent.com/sankarganeshgandhi/k8s/main/shared-configmap.yaml
  #- shared-configmap.yaml
  #- default-docker-registry.yaml
