# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

helmChartInflationGenerator:
- chartName: vault
  chartHome: helm-charts
  chartVersion: 0.13.0
  releaseName: vault
  values: vault-values-psql.yaml
  chartRepoUrl: https://helm.releases.hashicorp.com

configMapGenerator:
- name: vault-initdb-configmap
  files:
  - configs/vault-initdb.sql
- name: userconfig
  files:
    - configs/postgres.hcl

resources:
  - namespace.yaml
  - vault-postgres-secrets.yaml