# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

helmChartInflationGenerator:
- chartName: vault
  chartHome: helm-charts
  chartVersion: 0.13.0
  releaseName: hashicorp/vault
  values: vault-values.yaml
  chartRepoUrl: https://helm.releases.hashicorp.com

#resources:
#  - 