apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: vault-csr
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  ## $(cat ${TMPDIR}/${BASENAME}.csr | base64 | tr -d '\n')
  request: xxxxxx
  usages:
  - digital signature
  - key encipherment
  - client auth