apiVersion: v1
data:
  vault.ca: xxxxxx
  vault.crt: xxxxx
  vault.key: xxxxxx
kind: Secret
metadata:
  name: vault-tls
  namespace: vault
## kubectl create secret generic injector-tls \
##   --from-file=/home/gand/temp/vault/tls.crt --from-file=/home/gand/temp/vault/tls.key \
##   --namespace=vault \
##   --dry-run=client --output=yaml