{{- if .Values.vault.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "myservice1.fullname" . }}-ext-secrets
spec:
  backendType: vault
  data:
    - key: {{ .Values.vault.pathToSecrets }}
      name: username
      property: username
    - key: {{ .Values.vault.pathToSecrets }}
      name: password
      property: password
  kvVersion: 1
  vaultMountPoint: kubernetes
  vaultRole: {{ .Values.vault.appRole }}
  {{- end }}