# apiVersion: kubernetes-client.io/v1
# kind: ExternalSecret
# metadata:
#   name: {{ include "myservice1.fullname" . }}-ext-secrets
# spec:
#   backendType: vault
#   data:
#     - key: {{ .Values.vault.secret_path }}
#       name: username
#       property: username
#     - key: {{ .Values.vault.secret_path }}
#       name: password
#       property: password
#   kvVersion: 2
#   template:
#     data:
#       file.txt: |
#         <%= Buffer.from(JSON.stringify(JSON.parse(data.username).objKey)).toString("base64") %>
#     metadata:
#       labels:
#         label1: <%= JSON.parse(data.username).intKey %>
#         label2: <%= JSON.parse(data.username).objKey.strKey.replace(" ", "-") %>
#     stringData:
#       file.yaml: |
#         <%= yaml.dump(JSON.parse(data.username)) %>
#         <% let password = JSON.parse(data.password) %><% password.arrKey.forEach((e, i) => { %>arr_<%= i %>: <%= e %>
#         <% }) %>`
#   vaultMountPoint: kubernetes
#   vaultRole: "vault-role"