{{- if .Values.env -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reference-example-service.fullname" . }}-config
  labels:
    {{- include "reference-example-service.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end}}
{{- end }}