{{- if .Values.kafka.server -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ include "reference-example-service.kafka-server.name" . }}
  labels:
    {{- include "reference-example-service.labels" . | nindent 4 }}
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
      zookeper.connection.timeout.ms: 3000
      zookeper.session.timeout.ms: 3000
      controlled.shutdown.enable: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
        - name: zookeeper.electionPortBindRetry
          value: "100"
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}