{{- if .Values.kafka.topics -}}
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: Topic1
  labels:
    strimzi.io/cluster: {{ .Values.kafka.topics.kafkaClusterName }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
{{- end }}