apiVersion: v1
kind: Namespace
metadata:
  name: vault-operator
  labels:
    name: vault-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: vault-operator
spec:
  targetNamespaces:
  - vault-operator
  - vault
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: vault
  namespace: vault-operator
spec:
  channel: beta
  name: vault
  source: operatorhubio-catalog
  sourceNamespace: olm